# Generated by Django 3.1.6 on 2021-05-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageclass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageclass',
            name='Recognised',
        ),
        migrations.RemoveField(
            model_name='imageclass',
            name='text',
        ),
    ]
