# Generated by Django 3.1.6 on 2021-05-20 04:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageclass', '0002_auto_20210520_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclass',
            name='Image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
